### ISSUE TITLE
darkmode显示问题

### ISSUE THREAD

**Issue by anserme** [waylybaye/ServerCatFeedback#12]
![-7f8f9d16b885a39.jpg](http://img.pharcloud.com/images/2020/03/24/K0n7tROVAL9xkpRL.jpg)
可能是我的问题？

**Comment by anserme** [comment]
哦重新进去又好了，在Terminal中切换darkmode就会这样

**Comment by waylybaye** [comment]
1.0(14) 应该解决了

**Comment by anserme** [comment]
1.0（15）
![IMG_20200325_143444.jpg](http://img.pharcloud.com/images/2020/03/25/uHxgrVxcngjfwZT1.jpg)
![IMG_20200325_143503.jpg](http://img.pharcloud.com/images/2020/03/25/VJqcc8SkIIOgrM31.jpg)
