### ISSUE TITLE
非自带英文输入法在 ssh 界面无法正常输入

### ISSUE THREAD

**Issue by Kosette** [waylybaye/ServerCatFeedback#13]
测试了第三方中文输入法，自带日文输入法，在输入英文字符时均存在不能正常输入字符的情况。
中文输入法的英文模式下，输入空格后，后续字符不能正常输入，并且存在光标定位错误。

此外无法看到白色背景下的光标位置，top 命令显示不正常，内容断裂错位

**Comment by miniers** [comment]
🤣搜狗输入法 关闭英文联想，还是很诡异
![DA2C1C32-7665-4BE1-829E-12BCD75F5512](https://user-images.githubusercontent.com/2039910/77613168-fbcab500-6f64-11ea-96c3-4a2a49f35b52.gif)
