### ISSUE TITLE
添加多个（两个）服务器后的两个问题

### ISSUE THREAD

**Issue by Dukewill** [waylybaye/ServerCatFeedback#14]
_* 仅测试了通过 SSH Key 方式下添加两个服务器的情况，密码登录和更多服务器暂未测试。_

1. 重新打开 App 后，先添加的服务器会丢失 SSH Key 的选择状态（变成 None）；
2. 连接 SSH 后，右下角的可收缩快捷列表只能关闭一个，另一个点“X”只会收起列表。

**Comment by waylybaye** [comment]
1.0(17) 应该修复了

**Comment by Dukewill** [comment]
第二个问题解决了，第一个问题仍在。
进入SSH有几率出现 session closed提示，多试几次后会恢复。
![](https://cdn.jsdelivr.net/gh/Dukewill/jsdelivrCDN@dev/img/IMG_0523.jpg)

**Comment by waylybaye** [comment]
1.0(20) 应该修复了

**Comment by Dukewill** [comment]
已修复，辛苦！
