### ISSUE TITLE
processes 显示ui异常

### ISSUE THREAD

**Issue by tianguzhe** [waylybaye/ServerCatFeedback#2]
![photo_2020-03-24_15-51-59](https://user-images.githubusercontent.com/56765176/77401449-e67c4c00-6de7-11ea-9cf7-6306b9620b32.jpg)

**Comment by Kosette** [comment]
processes 显示不断的刷新覆盖，抖动，cpu 利用率，负载等数据无法正常显示

**Comment by waylybaye** [comment]
@tianguzhe 你的服务器什么系统和版本啊

**Comment by tianguzhe** [comment]
> @tianguzhe 你的服务器什么系统和版本啊

腾讯云 ubuntu 18.04

**Comment by Kosette** [comment]
@tianguzhe 更新最新的 tf 版本，将 terminal 字号调小，不断尝试，直到 terminal 里面能够正常显示 htop为止，可以尝试设置 fontsize=8

**Comment by waylybaye** [comment]
暂时去掉了这个功能
