### ISSUE TITLE
进入APP后，点击任意服务器进入二级菜单切换tab时很大概率跳回一级菜单

### ISSUE THREAD

**Issue by sky4sky** [waylybaye/ServerCatFeedback#24]

**Comment by waylybaye** [comment]
1.0(17) 应该修复了

**Comment by sky4sky** [comment]
> 1.0(17) 应该修复了

我这边测试并没有修复

**Comment by waylybaye** [comment]
你点哪个地方能出现这个问题 😂

**Comment by sky4sky** [comment]
> 你点哪个地方能出现这个问题 😂

打开APP后点击任意服务器进入二级菜单，之后点击底部导航栏进行切换操作，也就是status/docker/processes/scripts
不论processes是否载入，在切换tab时就会跳回一级菜单，（之前有一位提交的提到：服务器详情页右滑会跳回上级菜单类似并且这个bug也没有修复）
并且切换tab时，当前页面没有同步切换到点击的标签位置
- 不知道这么描述八爷能不能看懂😅``
