### ISSUE TITLE
输入服务器信息时有点鬼畜

### ISSUE THREAD

**Issue by anserme** [waylybaye/ServerCatFeedback#3]
文字会在输入框左右来回跳跃……

**Comment by waylybaye** [comment]
哪个的输入框

**Comment by tianguzhe** [comment]
在中文输入法下  编辑服务器name字段  会出现bug

**Comment by AFutureD** [comment]
用户名 输入框，中文输入法时。ssh key 的 Name 输入框，中文输入法时。两个使用英文输入时，有概率在 字符之间多个空格。

**Comment by waylybaye** [comment]
复现了 😂

**Comment by Dukewill** [comment]
另外输入法会挡住页面下半部分，不收起键盘无法选择“Show in Status”，有点影响体验。

**Comment by anserme** [comment]
而且输入空格并不会直接显示，只有输入非空格字符后才可以看到之前输入的空格

**Comment by rTnrWE** [comment]
有此问题

**Comment by waylybaye** [comment]
1.0(15) 应该修复了
