### ISSUE TITLE
[BUG]RSA密钥错误

### ISSUE THREAD

**Issue by iozxcvb** [waylybaye/ServerCatFeedback#39]
**请详细描述问题**RSA密钥错误

**iOS 和 App 的版本号**1.0.0

**截图（如果有）**
![photo_2020-05-03_11-58-33](https://user-images.githubusercontent.com/58126974/80898389-72fa2280-8d35-11ea-8496-d4e2742ecec5.jpg)

**Comment by waylybaye** [comment]
最新版 1.0.2(55) 应该修复啦
