### ISSUE TITLE
[BUG]连接失败后必须杀死后台才能连接

### ISSUE THREAD

**Issue by iozxcvb** [waylybaye/ServerCatFeedback#40]
**请详细描述问题**
服务器连接失败app内切换页面、返回主屏幕再进都不会再次尝试连接，必须杀后台再打开app才会尝试连接
**iOS 和 App 的版本号**
ios13.4.1，app商店1.0.1
[[**截图（如果有）**
![photo_2020-05-03_12-16-03](https://user-images.githubusercontent.com/58126974/80898652-85299000-8d38-11ea-8c03-12b57f210fcf.jpg)

**Comment by waylybaye** [comment]
最新版本 1.0.2(55) 应该修复啦，请验证下

**Comment by iozxcvb** [comment]
> 最新版本1.0.2（55）应该修复啦，请验证下

嗯没问题，修复了
